### ISSUE TITLE
Rotorcraft Sensor Calibration Refinements: ACCEL, MAG, MAG_CURRENT

### ISSUE THREAD

**Issue by hooperfly** [paparazzi/paparazzi#1599] opened 2016-04-14 19:00 UTC
It's a tedious process to calibrate sensors for rotorcraft and it seems we might be able to refine the process a bit based on the migration to `modules`. Case in point, the updated `mag_current` calibration that uses a module vs. the `subsystem` approach is a nice refinement. After a bit of thought, it seems we might be able to do the same for the `accel` and `mag` calibrations. 

Instead of having to enable `raw_sensor` telemetry and then stop/start the `server`, we could use the `modules` approach, similar to the updated `mag_current` approach, that leverages start/stop toggle button operations. 

The other refinement would be to add some inert `bracketing` constructs to the log files that would allow for detecting the start/stop of each type of calibration. This reduces the need to stop/start the server and supports a single log file that contains the `accel`, `mag`, `mag_current` calibration blocks. 

The goal would be to evolve the process while not impacting existing processes/tools that operate on the log files. If there is a `comment` line allowed in the <log>.data, it could be overloaded to create `data brackets` for detecting begin/end calibration blocks.

```
# BEGIN : ACCEL
...
# END : ACCEL
...
# BEGIN : MAG
...
# END : MAG
...
# BEGIN : MAG_CURRENT
...
# END : MAG_CURRENT
```

**Comment by flixr** [comment] 2016-04-14 19:29
Actually instead of running the calibration on a log, I would favour directly reading the messages from IVY.
I started a simple mag calibration script that does that in my calib_mag_live branch some time ago: https://github.com/flixr/paparazzi/commit/f67b7760e085e89ab7b0a53d84566350c90501c3

But I didn't continue since some ENAC students are apparently working on a nice calibration script/gui that does that. I had actually expected a pull request by now...

**Comment by hooperfly** [comment] 2016-04-14 19:35
Ok, that works too. Who would have status on the ENAC project?

**Comment by gautierhattenberger** [comment] 2016-04-15 09:36
The student project in itself is finished, but their code is not really usable right away, so we wanted to improve and polish it a bit before. The issue is we don't have much time for that. So at some point we may publish it as his and see who wants to work on it.
Remember they are first year students and it's their first programming project...

**Comment by agressiva** [comment] 2016-04-16 14:47
way not a module that make all calculations and save the values on the flash ? or a way to save the values on the settings tab using the persistent options ?

The way paparazzi is calibrated is very tedious and complicated for a ordinary user.

**Comment by flixr** [comment] 2016-04-17 10:39
Doing the optimization onboard would be a bit too heavy for most target MCUs right now... for a simple min/max calibration it would be doable.

**Comment by hooperfly** [comment] 2016-04-19 00:26
@flixr I looked at your calib_mag_live branch. I like it and was thinking about using Qt or other, instead of GTK. Any thoughts? Thinking about making a web based calibration tool using the PPRZLINK and the Flask stuff I've been using with the FRC.

**Comment by flixr** [comment] 2016-04-19 07:47
Unless there is significant benefit of using Qt for that case, I would suggest to stick with GTK.
We have no dependencies on Qt yet...

**Comment by gautierhattenberger** [comment] 2016-04-19 09:43
Our students are learning to use Qt only and they are using it in their projects as well. It is the case for the calibration tool they made, the pprz_center, and so on. I know it is not really helping, but at least now we can give them Python project and not Java only with the new Enac courses...

**Comment by flixr** [comment] 2016-12-29 17:34
See #1977

**Comment by hooperfly** [comment] 2016-12-29 18:49
@flixr I'll try out the new python mag tool referenced in #1977

**Comment by OpenUAS** [comment] 2017-05-31 11:07
@hooperfly Any update on this (issue)?

**Comment by podhrmic** [comment] 2017-08-26 23:00
Can we close this or do we need further updates/refinements? @hooperfly @flixr

**Comment by hooperfly** [comment] 2017-08-29 05:22
@podhrmic well we have added more options for calibration. I'll review the current process as I have a few aircraft to calibrate this week. I'll leave my thoughts here when I'm done. Thanks for the ping.

**Comment by gautierhattenberger** [comment] 2021-12-13 10:21
We still need a proper HMI, but closing this proposol

**Closed by gautierhattenberger** 2021-12-13 10:21 UTC
Labels: Won't fix
