### ISSUE TITLE
Quaternion Controller Axis priority for Thrust Vectoring Vehicles with heading saturation

### ISSUE THREAD

**Issue by dewagter** [paparazzi/paparazzi#161] opened 2012-03-15 08:16 UTC
In the case of heading saturation (vehicle can not follow the command: which happens a lot with hovering planes and quadshots) the controller should focus on attitude first.

Now the controller compares the actual and desired pitch. But when the commanded heading and actual heading diverge you end up steering in the wrong direction. E.g. heading setpoint = north with 20 deg pitch down and actual heading east, then the quadshot or plane or quadrotor should roll 20deg left instead to have the attititude point north.

(0,0,1) \* Rmat-setpoint = requested thrust vector
(0,0,1) \* Rmat-attitude = actual vect

Pitch&roll command = rotation between the 2

Heading is done afterwards

---
##

**Comment by OpenUAS** [comment] 2015-04-29 17:36
Temp assigned as reminder to validate if still not fixed by e.g. EwoudSmeur

**Comment by podhrmic** [comment] 2015-04-29 17:44
Maybe I am not reading this correctly, but isn't it just "not properly calibrated gains" issue?

**Comment by benlaurie** [comment] 2015-04-29 19:50
Surely not. For example, if I give the command "yaw left 90 degrees and roll left (according to current heading) 10 degrees", then if the yaw command can be obeyed infinitely fast, that roll is actually a pitch.

That's not about gains. Its about getting the physics right.

**Comment by flixr** [comment] 2015-06-25 15:45
@dewagter do you have any good ideas on how to fix this (also taking the reference generator into account)?

**Comment by OpenUAS** [comment] 2015-12-03 14:23
IMHO an issue like this should be blocking since it leads quite often to an rotorcraft flying in an uncontrolled fashion for regular users. De-assign since assignment was as a reminder to self.

**Comment by flixr** [comment] 2015-12-03 14:26
Well, I would consider blocking as something that - well - blocks a release.
Since we don't have an exact idea where the issue is or how to fix it and have had many successful flights, I would not consider this blocking.

**Comment by OpenUAS** [comment] 2015-12-10 22:30
Fine set to overnext release

**Comment by gautierhattenberger** [comment] 2018-03-12 10:17
closing this due to timeout (and probably solved by INDI mixing if needed)

**Closed by gautierhattenberger** 2018-03-12 10:17 UTC
Labels: Airborne, Major, Pending removal, Rotorcraft
