### ISSUE TITLE
Add a way to use qgroundcontrol with paparazzi airborne software.

### ISSUE THREAD

**Issue by esden** [paparazzi/paparazzi#13] opened 2010-11-12 03:43 UTC
This is a big topic with several unknowns.

qgroundcontrol uses mavlink protocol to communicate directly with the airborne software.

mavlink is not a replacement for ivy in any way. It is very similar to the protocol we use between the airborne software and the link.ml application. (DOWNLINK protocol?)

There are several solutions:

 * Replace DOWNLINK protocol with mavlink (that implies changing or reimplementing link.ml that translates airborne protocol to ivy). Add support of ivy in qgroundcontrol or make link.ml rebroadcast mavlink so that qgroundcontrol can connect to that.

  * Add support of mavlink parallel to the current DOWNLINK protocol

  * Implement a translator from DOWNLINK to mavlink and/or ivy to mavlink

**Comment by flixr** [comment] 2015-03-25 14:57
If anyone wants to test this what currently already works with qGroundcontrol, please check out the [mavlink module] (http://docs.paparazziuav.org/latest/module__mavlink.html)

**Comment by agressiva** [comment] 2015-03-25 17:35
felix, its only for rotorcraft ?
i tried compile for fixedwing and get some error about UINT16_MAX

**Comment by flixr** [comment] 2015-03-25 17:42
It should work for fixedwing as well... compiles here for e.g. Microjet_LisaM

**Comment by flixr** [comment] 2015-03-25 17:44
But to make sure UINT16_MAX is defined in all cases I added the stdint.h include with 11ff2c49239e0592eb7b176765db930e6b458c32
So please try again with latest master...

**Comment by flixr** [comment] 2015-11-03 22:44
Closing this as duplicate of #119, since if mavlink is "properly" integrated it will work with QGroundControl

**Closed by flixr** 2015-11-03 22:44 UTC
Labels: Duplicate, Enhancement, Ground Segment

**Comment by dewagter** [comment] 2015-11-04 08:47
Until then use mavlink-ivy-interface.

github.com/mavlink/

**Comment by flixr** [comment] 2015-11-04 09:01
mavlink-ivy-interface has even less functionality than our current mavlink module (which already works with QGroundControl, just doesn't provide all of the messages you might want, no mission interface, etc)....
