### ISSUE TITLE
[gcs] map tiles mixed up

### ISSUE THREAD

**Issue by bartslinger** [paparazzi/paparazzi#1747] opened 2016-06-19 08:03 UTC
From the menu in the GCS, I selected Maps->Dump map of Tiles. The generated *.png already shows the tiles mixed up, and that's also how they appear in the GCS if I load the file. Tried both google and bing as map source, but that did not solve the problem.
![screenshot from 2016-06-19 10 02 21](https://cloud.githubusercontent.com/assets/8672355/16176104/f61b90c2-3604-11e6-8b6a-8b25298434d0.png)

**Comment by OpenUAS** [comment] 2017-02-14 18:09
Will test and see to reproduce asap

**Comment by gautierhattenberger** [comment] 2017-07-25 15:14
did anyone managed to reproduce this bug ?

**Comment by podhrmic** [comment] 2017-07-25 16:30
Yes, this is what it looks like on Ubuntu 16.04 and master pprz.

First, this is the GCS view with a rectangle select for the tile dump:
![gcs](https://user-images.githubusercontent.com/2790461/28582855-cbfd7f8c-711b-11e7-95a6-bd9517e37834.png)

This is the resulting tile dump file:
![tiles](https://user-images.githubusercontent.com/2790461/28582869-d7245f2a-711b-11e7-9bbe-e3282e6dd18c.png)

Obviously wrong. On the other side, I didn't know about that feature (Dump Tiles) until I read this issue, so perhaps it can be removed if it is too hard to fix?

**Comment by OpenUAS** [comment] 2017-08-03 10:03
I yes, could reproduce, on latest, de feature is uest and looking at it maybe has to do with wrong tile zoomlevel, recal that changed to higher in the past, but maybe not this part.

**Comment by gautierhattenberger** [comment] 2018-06-06 17:54
closing as won't be fixed in current GCS
see https://github.com/paparazzi/paparazzi/projects/2

**Closed by gautierhattenberger** 2018-06-06 17:54 UTC
Labels: GCS, Minor, Won't fix
