### ISSUE TITLE
Flight Recorder GPS in ARDrone 2 not working

### ISSUE THREAD

**Issue by pache1211** [paparazzi/paparazzi#1595] opened 2016-04-06 14:07 UTC
Hi I saw that Issue #1295 was closed I was wondering if the sirf mode is working now, I need to use the flight recorder in my project, so I really need to see if it works with paparazzi.
Thank you

**Comment by flixr** [comment] 2016-04-07 14:56
I don't think it is (there have been no changes) or if it even actually ever worked for the Flight recorder.

But I'm closing this as a duplicate of #1295

**Closed by flixr** 2016-04-07 14:56 UTC
Labels: Duplicate
