### ISSUE TITLE
ARDrone2 will still take of with one blocked prop

### ISSUE THREAD

**Issue by kevindehecker** [paparazzi/paparazzi#1009] opened 2014-12-06 11:32 UTC
Sometimes, my ARDrone2 does not start properly because one or more of the props won't start, while the others start normally. In this case, I'm still allowed to take off either with ATT or in NAV mode, crashing as a consequence.

While most of the time this is initially caused by a hardware issue, this behavior does not seem right. Especially since the default behavior when blocking one *after* a normal engines-start immediately kills all props.

I think that should also happen in case of this problem.

The problem is easily reproduced by manually blocking one of the props and performing a normal start engines. Three props will start normally, one will not, and you are allowed to take off.

**Comment by flixr** [comment] 2015-02-10 17:32
So? Is anyone who can actually reproduce this looking into the issue??

**Comment by fvantienen** [comment] 2015-03-01 22:40
Since I'm not able to reproduce this anymore and I think some of the problems were caused by #1117 I think we should close this.

**Closed** 2015-03-01 22:41 UTC
Labels: ARDrone2
