### ISSUE TITLE
If session is saved without ever being run the session is emptied

### ISSUE THREAD

**Issue by OpenUAS** [paparazzi/paparazzi#891] opened 2014-11-03 16:50 UTC
As user I like to create a session. If anew one is created and session is saved without being run the session is emptied
##

**Comment by flixr** [comment] 2015-11-03 21:53
Can't reproduce it... or I don't understand the issue...

**Comment by flixr** [comment] 2016-12-16 15:24
Closing this issue... @OpenUAS if you can provide steps to reproduce this, feel free to reopen it..

**Closed by flixr** 2016-12-16 15:24 UTC
Labels: Incomplete, Minor, Paparazzi Center, Unable to reproduce
